GET http://localhost:8000/

###
GET http://localhost:8000/api/ok
###

GET http://localhost:8000/api/time

###
GET http://localhost:8000/api/users 
###
GET http://localhost:8000/api/metrics
###
GET http://localhost:8000/api/users/1
###
POST http://localhost:8000/api/users
Content-Type: application/json

  {
    "id": 3,
    "name": "john Doe",
    "contact_phone": 34557299,
    "phone_verified": true,
    "email": "john.doe@example.com",
    "email_verified": true,
    "confirmation_code": 12345,
    "password": "password123"
  }
###
PUT http://localhost:8000/api/users/2
Content-Type: application/json

{
    
    "email": "janesmitha@gmail.com"
    
}
###
GET http://localhost:8000/api/states

###
GET http://localhost:8000/api/states/4

###
POST http://localhost:8000/api/states
 Content-Type: application/json

 {
  "id": 6,
  "name": "Miami",
  "code": "MM"
}

###
PUT http://localhost:8000/api/states/3
 Content-Type: application/json

  {
    
    "name": "kutus"
    
  }

###
GET http://localhost:8000/api/cities

###
GET http://localhost:8000/api/cities/3
###
POST http://localhost:8000/api/cities
 Content-Type: application/json


    {
       "id": 4,
       "name": "Atlanta",
       "state_id": 6
    }

###
PUT http://localhost:8000/api/cities/5
 Content-Type: application/json

  { 

    "name": "Florida"
  }
###
DELETE http://localhost:8000/api/cities/4

//drivers queries
###
GET http://localhost:8000/api/drivers
###
GET http://localhost:8000/api/drivers/1
###
POST http://localhost:8000/api/drivers
Content-Type: application/json

{
  "id": 3,
  "car_make": "lamborghini",
  "car_model": "Urus",
  "car_year": 2018,
  "user_id": 1,
  "online": true,
  "delivering": true
  
}

###
PUT http://localhost:8000/api/drivers/1
 Content-Type: application/json

 {
  "car_model":"Crown"
 }

###
DELETE http://localhost:8000/api/drivers/3

//address queries
###
GET http://localhost:8000/api/address

###
GET http://localhost:8000/api/address/3
###
POST http://localhost:8000/api/address
 Content-Type: application/json
 
 {
    "id": 4,
    "street_address_1": "126 Main St",
    "street_address_2": "Apt 1",
    "zip_code": 90001,
    "delivery_instructions": "Leave at the front door",
    "user_id": 1,
    "city_id": 2
    
  }

###
PUT http://localhost:8000/api/address/4
 Content-Type: application/json

 {
  "street_address_1":"120 Uptown",
  "stree_address_2":"Apt 2"
 }  
###
DELETE http://localhost:8000/api/address/4

//restaurant queries
###
GET http://localhost:8000/api/restaurant
###
GET http://localhost:8000/api/restaurant/4
###
POST http://localhost:8000/api/restaurant
 Content-Type: application/json

 {
   "id": 2,
    "name": "Pizza Paradise",
    "street_address": "456 Flavor St",
    "zip_code": 80302,
    "city_id": 3
 }

  
###
PUT http://localhost:8000/api/restaurant/2
 Content-Type: application/json
  
  {
    "street_address":"213 Downyown"
  }
###
DELETE http://localhost:8000/api/restaurant/2  
